// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// alignedPipCpp
Rcpp::List alignedPipCpp(const Rcpp::RawVector& gammaRaw, int p, int numModels, int numDraws, int maxExact);
RcppExport SEXP _bayesrep_alignedPipCpp(SEXP gammaRawSEXP, SEXP pSEXP, SEXP numModelsSEXP, SEXP numDrawsSEXP, SEXP maxExactSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::RawVector& >::type gammaRaw(gammaRawSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type numModels(numModelsSEXP);
    Rcpp::traits::input_parameter< int >::type numDraws(numDrawsSEXP);
    Rcpp::traits::input_parameter< int >::type maxExact(maxExactSEXP);
    rcpp_result_gen = Rcpp::wrap(alignedPipCpp(gammaRaw, p, numModels, numDraws, maxExact));
    return rcpp_result_gen;
END_RCPP
}
// coallocationCpp
arma::mat coallocationCpp(const Rcpp::RawVector& gammaRaw, int p, int numModels, int numDraws, const Rcpp::IntegerVector& featureIdx);
RcppExport SEXP _bayesrep_coallocationCpp(SEXP gammaRawSEXP, SEXP pSEXP, SEXP numModelsSEXP, SEXP numDrawsSEXP, SEXP featureIdxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::RawVector& >::type gammaRaw(gammaRawSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type numModels(numModelsSEXP);
    Rcpp::traits::input_parameter< int >::type numDraws(numDrawsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type featureIdx(featureIdxSEXP);
    rcpp_result_gen = Rcpp::wrap(coallocationCpp(gammaRaw, p, numModels, numDraws, featureIdx));
    return rcpp_result_gen;
END_RCPP
}
// rpgVecCpp
arma::vec rpgVecCpp(double b, const arma::vec& c, int trunc);
RcppExport SEXP _bayesrep_rpgVecCpp(SEXP bSEXP, SEXP cSEXP, SEXP truncSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type c(cSEXP);
    Rcpp::traits::input_parameter< int >::type trunc(truncSEXP);
    rcpp_result_gen = Rcpp::wrap(rpgVecCpp(b, c, trunc));
    return rcpp_result_gen;
END_RCPP
}
// transferFeatureCpp
Rcpp::List transferFeatureCpp(const arma::mat& resp, const arma::mat& sqrtW, const arma::mat& X, arma::mat betaMatrix, arma::mat gammaMatrix, double sigmaSqScaled, double tauSq, int numMoves);
RcppExport SEXP _bayesrep_transferFeatureCpp(SEXP respSEXP, SEXP sqrtWSEXP, SEXP XSEXP, SEXP betaMatrixSEXP, SEXP gammaMatrixSEXP, SEXP sigmaSqScaledSEXP, SEXP tauSqSEXP, SEXP numMovesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type resp(respSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sqrtW(sqrtWSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type betaMatrix(betaMatrixSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type gammaMatrix(gammaMatrixSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaSqScaled(sigmaSqScaledSEXP);
    Rcpp::traits::input_parameter< double >::type tauSq(tauSqSEXP);
    Rcpp::traits::input_parameter< int >::type numMoves(numMovesSEXP);
    rcpp_result_gen = Rcpp::wrap(transferFeatureCpp(resp, sqrtW, X, betaMatrix, gammaMatrix, sigmaSqScaled, tauSq, numMoves));
    return rcpp_result_gen;
END_RCPP
}
// updateBetaGammaCpp
Rcpp::List updateBetaGammaCpp(const arma::vec& yScaled, const arma::mat& X, const arma::vec& xTx, arma::vec betaGroup, arma::mat gammaMatrix, int targetGroup, double sigmaSqScaled, double tauSqScaled, const arma::vec& thetaVec, double lambda2);
RcppExport SEXP _bayesrep_updateBetaGammaCpp(SEXP yScaledSEXP, SEXP XSEXP, SEXP xTxSEXP, SEXP betaGroupSEXP, SEXP gammaMatrixSEXP, SEXP targetGroupSEXP, SEXP sigmaSqScaledSEXP, SEXP tauSqScaledSEXP, SEXP thetaVecSEXP, SEXP lambda2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type yScaled(yScaledSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type xTx(xTxSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type betaGroup(betaGroupSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type gammaMatrix(gammaMatrixSEXP);
    Rcpp::traits::input_parameter< int >::type targetGroup(targetGroupSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaSqScaled(sigmaSqScaledSEXP);
    Rcpp::traits::input_parameter< double >::type tauSqScaled(tauSqScaledSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type thetaVec(thetaVecSEXP);
    Rcpp::traits::input_parameter< double >::type lambda2(lambda2SEXP);
    rcpp_result_gen = Rcpp::wrap(updateBetaGammaCpp(yScaled, X, xTx, betaGroup, gammaMatrix, targetGroup, sigmaSqScaled, tauSqScaled, thetaVec, lambda2));
    return rcpp_result_gen;
END_RCPP
}
// updateLambda2Cpp
Rcpp::List updateLambda2Cpp(double lambda2, const arma::vec& thetaVec, const arma::vec& mCounts, int numModels, double priorShape, double priorRate, double proposalSd);
RcppExport SEXP _bayesrep_updateLambda2Cpp(SEXP lambda2SEXP, SEXP thetaVecSEXP, SEXP mCountsSEXP, SEXP numModelsSEXP, SEXP priorShapeSEXP, SEXP priorRateSEXP, SEXP proposalSdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type thetaVec(thetaVecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mCounts(mCountsSEXP);
    Rcpp::traits::input_parameter< int >::type numModels(numModelsSEXP);
    Rcpp::traits::input_parameter< double >::type priorShape(priorShapeSEXP);
    Rcpp::traits::input_parameter< double >::type priorRate(priorRateSEXP);
    Rcpp::traits::input_parameter< double >::type proposalSd(proposalSdSEXP);
    rcpp_result_gen = Rcpp::wrap(updateLambda2Cpp(lambda2, thetaVec, mCounts, numModels, priorShape, priorRate, proposalSd));
    return rcpp_result_gen;
END_RCPP
}
// updateSigmaSqCpp
double updateSigmaSqCpp(const arma::vec& y, const arma::mat& X, const arma::mat& betaMatrix, double intercept, double learningRate, double nu0, double sigma0Sq);
RcppExport SEXP _bayesrep_updateSigmaSqCpp(SEXP ySEXP, SEXP XSEXP, SEXP betaMatrixSEXP, SEXP interceptSEXP, SEXP learningRateSEXP, SEXP nu0SEXP, SEXP sigma0SqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type betaMatrix(betaMatrixSEXP);
    Rcpp::traits::input_parameter< double >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< double >::type learningRate(learningRateSEXP);
    Rcpp::traits::input_parameter< double >::type nu0(nu0SEXP);
    Rcpp::traits::input_parameter< double >::type sigma0Sq(sigma0SqSEXP);
    rcpp_result_gen = Rcpp::wrap(updateSigmaSqCpp(y, X, betaMatrix, intercept, learningRate, nu0, sigma0Sq));
    return rcpp_result_gen;
END_RCPP
}
// updateThetaCpp
Rcpp::List updateThetaCpp(arma::vec thetaVec, const arma::vec& mCounts, double aPrior, double bPrior, double lambda2, int numModels, int numSweeps);
RcppExport SEXP _bayesrep_updateThetaCpp(SEXP thetaVecSEXP, SEXP mCountsSEXP, SEXP aPriorSEXP, SEXP bPriorSEXP, SEXP lambda2SEXP, SEXP numModelsSEXP, SEXP numSweepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type thetaVec(thetaVecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mCounts(mCountsSEXP);
    Rcpp::traits::input_parameter< double >::type aPrior(aPriorSEXP);
    Rcpp::traits::input_parameter< double >::type bPrior(bPriorSEXP);
    Rcpp::traits::input_parameter< double >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< int >::type numModels(numModelsSEXP);
    Rcpp::traits::input_parameter< int >::type numSweeps(numSweepsSEXP);
    rcpp_result_gen = Rcpp::wrap(updateThetaCpp(thetaVec, mCounts, aPrior, bPrior, lambda2, numModels, numSweeps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bayesrep_alignedPipCpp", (DL_FUNC) &_bayesrep_alignedPipCpp, 5},
    {"_bayesrep_coallocationCpp", (DL_FUNC) &_bayesrep_coallocationCpp, 5},
    {"_bayesrep_rpgVecCpp", (DL_FUNC) &_bayesrep_rpgVecCpp, 3},
    {"_bayesrep_transferFeatureCpp", (DL_FUNC) &_bayesrep_transferFeatureCpp, 8},
    {"_bayesrep_updateBetaGammaCpp", (DL_FUNC) &_bayesrep_updateBetaGammaCpp, 10},
    {"_bayesrep_updateLambda2Cpp", (DL_FUNC) &_bayesrep_updateLambda2Cpp, 7},
    {"_bayesrep_updateSigmaSqCpp", (DL_FUNC) &_bayesrep_updateSigmaSqCpp, 7},
    {"_bayesrep_updateThetaCpp", (DL_FUNC) &_bayesrep_updateThetaCpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_bayesrep(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
