# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

alignedPipCpp <- function(gammaRaw, p, numModels, numDraws, maxExact = 7L) {
    .Call(`_bayesrep_alignedPipCpp`, gammaRaw, p, numModels, numDraws, maxExact)
}

coallocationCpp <- function(gammaRaw, p, numModels, numDraws, featureIdx) {
    .Call(`_bayesrep_coallocationCpp`, gammaRaw, p, numModels, numDraws, featureIdx)
}

rpgVecCpp <- function(b, c, trunc = 200L) {
    .Call(`_bayesrep_rpgVecCpp`, b, c, trunc)
}

transferFeatureCpp <- function(resp, sqrtW, X, betaMatrix, gammaMatrix, sigmaSqScaled, tauSq, numMoves) {
    .Call(`_bayesrep_transferFeatureCpp`, resp, sqrtW, X, betaMatrix, gammaMatrix, sigmaSqScaled, tauSq, numMoves)
}

updateBetaGammaCpp <- function(yScaled, X, xTx, betaGroup, gammaMatrix, targetGroup, sigmaSqScaled, tauSqScaled, thetaVec, lambda2) {
    .Call(`_bayesrep_updateBetaGammaCpp`, yScaled, X, xTx, betaGroup, gammaMatrix, targetGroup, sigmaSqScaled, tauSqScaled, thetaVec, lambda2)
}

updateLambda2Cpp <- function(lambda2, thetaVec, mCounts, numModels, priorShape, priorRate, proposalSd) {
    .Call(`_bayesrep_updateLambda2Cpp`, lambda2, thetaVec, mCounts, numModels, priorShape, priorRate, proposalSd)
}

updateSigmaSqCpp <- function(y, X, betaMatrix, intercept = 0.0, learningRate = 1.0, nu0 = 1.0, sigma0Sq = 1.0) {
    .Call(`_bayesrep_updateSigmaSqCpp`, y, X, betaMatrix, intercept, learningRate, nu0, sigma0Sq)
}

updateThetaCpp <- function(thetaVec, mCounts, aPrior, bPrior, lambda2, numModels, numSweeps = 1L) {
    .Call(`_bayesrep_updateThetaCpp`, thetaVec, mCounts, aPrior, bPrior, lambda2, numModels, numSweeps)
}

